USE [master]
GO

/****** Object:  Database [minibit]    Script Date: 08/08/2022 15:26:58 ******/
DROP DATABASE [minibit]
GO

/****** Object:  Database [minibit]    Script Date: 08/08/2022 15:26:58 ******/
CREATE DATABASE [minibit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'minibit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\minibit.mdf' , SIZE = 598016KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'minibit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\minibit_log.ldf' , SIZE = 10493952KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [minibit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [minibit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [minibit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [minibit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [minibit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [minibit] SET ARITHABORT OFF 
GO

ALTER DATABASE [minibit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [minibit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [minibit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [minibit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [minibit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [minibit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [minibit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [minibit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [minibit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [minibit] SET  DISABLE_BROKER 
GO

ALTER DATABASE [minibit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [minibit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [minibit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [minibit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [minibit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [minibit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [minibit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [minibit] SET RECOVERY FULL 
GO

ALTER DATABASE [minibit] SET  MULTI_USER 
GO

ALTER DATABASE [minibit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [minibit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [minibit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [minibit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [minibit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [minibit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [minibit] SET  READ_WRITE 
GO

